#!/usr/bin/env node
/**
 * Automated setup script for frontend environment variables
 * Reads deployed program addresses from scripts directory
 */

const fs = require('fs');
const path = require('path');

console.log('🔧 Setting up frontend environment variables...\n');

// Read slab account info
const slabAccountPath = path.join(__dirname, '../scripts/slab-account.json');
const routerInfoPath = path.join(__dirname, '../scripts/router-info.json');

if (!fs.existsSync(slabAccountPath)) {
  console.error('❌ Error: scripts/slab-account.json not found');
  console.log('   Run scripts/initialize-slab.ts first to deploy the slab program\n');
  process.exit(1);
}

if (!fs.existsSync(routerInfoPath)) {
  console.error('❌ Error: scripts/router-info.json not found');
  console.log('   Run scripts/initialize-router.ts first to deploy the router program\n');
  process.exit(1);
}

const slabInfo = JSON.parse(fs.readFileSync(slabAccountPath, 'utf-8'));
const routerInfo = JSON.parse(fs.readFileSync(routerInfoPath, 'utf-8'));

console.log('✅ Found deployed program info:\n');
console.log(`   Slab Account:    ${slabInfo.slabAccount}`);
console.log(`   Slab Program:    ${slabInfo.programId}`);
console.log(`   Router Registry: ${routerInfo.registryAccount}`);
console.log(`   Router Program:  ${routerInfo.programId}\n`);

// Generate .env.local content
const envContent = `# Percolator Program Addresses (Devnet)
# Auto-generated by setup-env.js on ${new Date().toISOString()}

# Slab Program
NEXT_PUBLIC_SLAB_PROGRAM_ID=${slabInfo.programId}
NEXT_PUBLIC_SLAB_ACCOUNT=${slabInfo.slabAccount}
NEXT_PUBLIC_INSTRUMENT_ID=${slabInfo.instrumentId}

# Router Program
NEXT_PUBLIC_ROUTER_PROGRAM_ID=${routerInfo.programId}
NEXT_PUBLIC_ROUTER_REGISTRY=${routerInfo.registryAccount}

# Authority
NEXT_PUBLIC_AUTHORITY=${routerInfo.authority}

# Network
NEXT_PUBLIC_SOLANA_NETWORK=devnet
NEXT_PUBLIC_SOLANA_RPC_URL=https://api.devnet.solana.com

# API
NEXT_PUBLIC_API_URL=http://localhost:3000
`;

// Write .env.local
const envPath = path.join(__dirname, '.env.local');
fs.writeFileSync(envPath, envContent);

console.log('✅ Created .env.local with deployed addresses\n');
console.log('📋 Environment Variables:');
console.log(envContent);
console.log('\n🎉 Setup complete! You can now run:');
console.log('   npm run dev\n');

