# Cargo configuration for Percolator BPF builds

# Only use sbf target when explicitly building for BPF
# For normal builds and tests, use default target

[target.sbf-solana-solana]
# Use sbpf-linker when building for BPF target
linker = "sbpf-linker"
