name: Build for Devnet

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-programs:
    name: Build Solana Programs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Build Programs
        run: |
          cargo-build-sbf
      
      - name: Upload Programs
        uses: actions/upload-artifact@v4
        with:
          name: solana-programs
          path: target/deploy/*.so
          retention-days: 7

